apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradio-app
  labels:
    app: gradio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gradio-app
  template:
    metadata:
      labels:
        app: gradio-app
    spec:
      containers:
      - name: gradio-app
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/gradio-app:latest
        ports:
        - containerPort: 7860
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: gradio-app-service
spec:
  selector:
    app: gradio-app
  ports:
  - port: 80
    targetPort: 7860
  type: LoadBalancer
